name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main  # Adjust this if you deploy from a different branch
  pull_request:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        id: node-version
        run: echo "NODE_VERSION=$(cat .node-version)" >> $GITHUB_ENV

      - name: Use Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install dependencies
        run: npm install

      - name: Build (if applicable)
        run: |
          if [ -f package.json ] && grep -q '"build":' package.json; then
            npm run build
          else
            echo "No build script found, skipping..."
          fi

      - name: Create deployment package
        run: zip -r app.zip . -x "*.git*"
        
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v20
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.AWS_EB_APPLICATION }}
          environment_name: ${{ secrets.AWS_EB_ENVIRONMENT }}
          region: ${{ secrets.AWS_REGION }}
          version_label: ${{ github.sha }}
          deployment_package: app.zip